/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CursoForm: typeof import('./components/CursoForm.vue')['default']
    CursoForms: typeof import('./components/CursoForms.vue')['default']
    CursoList: typeof import('./components/CursoList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UsuarioForm: typeof import('./components/UsuarioForm.vue')['default']
    UsuarioList: typeof import('./components/UsuarioList.vue')['default']
  }
}
